### ISSUE TITLE
"No module named 'picamera'" when python3 init.py was executed

### ISSUE THREAD

**Issue by VictorTagayun** [CoderBotOrg/coderbot#98]
```
(coderbot) pi@raspberrypi:~/coderbot $ python3 init.py
Traceback (most recent call last):
  File "init.py", line 23, in <module>
    import main
  File "/home/pi/coderbot/main.py", line 10, in <module>
    import picamera
ImportError: No module named 'picamera'
(coderbot) pi@raspberrypi:~/coderbot $ 
```

**Comment by previ** [comment]
looks like we are missing picamera in the requirements.txt file.

**Comment by avivace** [comment]
From 13ccfcb28fb2e3c58d2136219d7106c2e5791ecc on, requirements are split between 2 files. Check the README for more info.
